### ISSUE TITLE
Unused replication slots in secondary replicas

### ISSUE THREAD

**Issue by fredkanye** [cloudnative-pg/cloudnative-pg.github.io#215]
Secondary replicas automatically create unused replication slots between them. Even when dropped with `SELECT pg_drop_replication_slot('slot_name');`, they re-appear after a few minutes.

**Comment by sxd** [comment]
Hello @fredkanye 

This issue trackers is for the cloudnative-pg.io website, please if you have an issue with the operator or something else, refer to the proper repository here `github.com/cloudnative-pg/cloudnative-pg`

Regards,
