### ISSUE TITLE
Properly display links

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg.github.io#35]
In the blog page it is hard to understand which text is actually part of a hyperlink. Can this be fixed please?

**Comment by mmanieri** [comment]
@gbartolini, good catch.  Intention was for blog links to be Red #1 (#E63054).  Look ok to you?

**Screenshot**
![Blog-link](https://user-images.githubusercontent.com/13258069/168113253-b5b81314-8ee0-402f-bf29-687a1b44a666.png)

**Comment by gbartolini** [comment]
Yep, that's fine, thanks
