### ISSUE TITLE
Redirect 1.15.1 and 1.15.0 docs to 1.15 folder

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg.github.io#60]
With #57 being merged, we should add redirects from the previous 1.15.1 and 1.15.0 versions of the documentation to the 1.15 one.

**Comment by drsm79** [comment]
Hugo has this natively supported via aliases. I think that's preferable to manually making redirects https://gohugo.io/content-management/urls/#aliases
